# This file was generated by GoReleaser. DO NOT EDIT.
cask "ftm510d" do
  name "ftm510d"
  desc "Programmer for the Yaesu FTM-510D"
  homepage "https://github.com/zm0ra/ftm510d-releases"
  version "0.9.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ftm510d"

  on_macos do
    on_intel do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_darwin_amd64.tar.gz"
      sha256 "34070184eed2a64d473e4b51a957dceba07b8236ec31a30288dc6091895ffc96"
    end
    on_arm do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_darwin_arm64.tar.gz"
      sha256 "ed209e65d38d9defc6c8805fdd5fbd528b96e78ae0a410181483177de01a2cbc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_linux_amd64.tar.gz"
      sha256 "da3a074b829c4f6255768905dfa0b9f7b20592e71d09b19d9c001d7228de9903"
    end
    on_arm do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_linux_arm64.tar.gz"
      sha256 "cc34cc701f1883b0c756e786b848e3660f67a15778d7013f166108922b244b01"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ftm510d"]
    end
  end

  # No zap stanza required
end
