# This file was generated by GoReleaser. DO NOT EDIT.
cask "ftm510d" do
  name "ftm510d"
  desc "Programmer for the Yaesu FTM-510D"
  homepage "https://github.com/zm0ra/ftm510d-releases"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ftm510d"

  on_macos do
    on_intel do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_darwin_amd64.tar.gz"
      sha256 "4c51f4f4b9ea78b94dc1a86bb0c59c4944e02afb67910bcc66c5c62cb180167b"
    end
    on_arm do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_darwin_arm64.tar.gz"
      sha256 "bdbba87a458ae91dd6993467d0b0972e43d384104094b65d6409b0dad05e5170"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_linux_amd64.tar.gz"
      sha256 "73da98f8aedd5a983e33acacfa635d77a9426457dc78b8f1836c4eb9fa329cd8"
    end
    on_arm do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_linux_arm64.tar.gz"
      sha256 "51d345f1e2e8cd4e8475b225eed5c88bcd3eaa1f110b7d0045060ab02bd7b392"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ftm510d"]
    end
  end

  # No zap stanza required
end
