# This file was generated by GoReleaser. DO NOT EDIT.
cask "ftm510d" do
  name "ftm510d"
  desc "Programmer for the Yaesu FTM-510D"
  homepage "https://github.com/zm0ra/ftm510d-releases"
  version "0.9.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ftm510d"

  on_macos do
    on_intel do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_darwin_amd64.tar.gz"
      sha256 "000d72ec97bf705b54ab4c1c3c0b1a8e0d731e6753147a0bd5af7227a16722a4"
    end
    on_arm do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_darwin_arm64.tar.gz"
      sha256 "c478d653c81e9bb58a3ad2d7e829181ef45e70798b9ddfac8239e00bf7c3fc78"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_linux_amd64.tar.gz"
      sha256 "18091f76eba9b1bb777062ea90720c503507183e7e1b68bf67e26452b0a018cc"
    end
    on_arm do
      url "https://github.com/zm0ra/ftm510d-releases/releases/download/v#{version}/ftm510d_#{version}_linux_arm64.tar.gz"
      sha256 "502a9cdd2abdfef779ccb1bd9b28ce80a4f9d60abd92c2e9b53bdead2ae592ff"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ftm510d"]
    end
  end

  # No zap stanza required
end
